baseURL = "https://zen-keller-38c439.netlify.com"
languageCode = "en-us"
title = "Chattanooga Democratic Socialists of America"
[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Events"
  identifier = "events"
  url = "/events/"
  weight = 3
[[menu.main]]
  name = "Donate"
  identifier = "donate"
  url = "/donate/"
  weight = 4
[[menu.main]]
  name = "Join Us"
  identifier = "join"
  url = "/join/"
  weight = 2
[params]
  logo = "img/dsa-logo.png"
	facebook = "ChattanoogaDemocraticSocialistsofAmerica"
	twitter = "dsa_chatt"
	email = "chattanoogadsa@gmail.com"
