version: "3"

services:

  hugo:
    build:
      dockerfile: docker/hugo/Dockerfile
      context: .
      args:
        DOCKER_UID: ${DOCKER_UID:-1000}
        DOCKER_GID: ${DOCKER_GID:-1000}
        HUGO_VERSION: ${HUGO_VERSION:-0.31}
    ports:
    - "1313:1313"
    volumes:
      - .:/app