[build]

  # how to build the static site
  command="hugo"

  # where the final site is generated
  publish="public"

[context.production.environment]
  HUGO_VERSION="0.31"
[context.branch-deploy.environment]
  HUGO_VERSION="0.31"
